-- This entity will contain folded key rows for each row originating from a super parent
-- entity. It will be used to track which counties should have access to a particular row
--  of data.

CREATE TABLE CNTYOWNT
(
    ENTITY_ID char(10) NOT NULL, -- The identifier of the parent entity Placement Home row to be owned by 1 or more counties.
    ENTITY_CD char(2) NOT NULL, -- P for Placement Home and S for Substitute Care Provider
    MULTI_FLG char(1) NOT NULL, -- This flag indicates whether multiple counties have access to a particular row.
    CTY_00_FLG char(1) NOT NULL,
    CTY_01_FLG char(1) NOT NULL, -- A flag used to determine if the county whose number matches the number of the attribute has authority to view a particular row.
    CTY_02_FLG char(1) NOT NULL,
    CTY_03_FLG char(1) NOT NULL,
    CTY_04_FLG char(1) NOT NULL,
    CTY_05_FLG char(1) NOT NULL,
    CTY_06_FLG char(1) NOT NULL,
    CTY_07_FLG char(1) NOT NULL,
    CTY_08_FLG char(1) NOT NULL,
    CTY_09_FLG char(1) NOT NULL,
    CTY_10_FLG char(1) NOT NULL,
    CTY_11_FLG char(1) NOT NULL,
    CTY_12_FLG char(1) NOT NULL,
    CTY_13_FLG char(1) NOT NULL,
    CTY_14_FLG char(1) NOT NULL,
    CTY_15_FLG char(1) NOT NULL,
    CTY_16_FLG char(1) NOT NULL,
    CTY_17_FLG char(1) NOT NULL,
    CTY_18_FLG char(1) NOT NULL,
    CTY_19_FLG char(1) NOT NULL,
    CTY_20_FLG char(1) NOT NULL,
    CTY_21_FLG char(1) NOT NULL,
    CTY_22_FLG char(1) NOT NULL,
    CTY_23_FLG char(1) NOT NULL,
    CTY_24_FLG char(1) NOT NULL,
    CTY_25_FLG char(1) NOT NULL,
    CTY_26_FLG char(1) NOT NULL,
    CTY_27_FLG char(1) NOT NULL,
    CTY_28_FLG char(1) NOT NULL,
    CTY_29_FLG char(1) NOT NULL,
    CTY_30_FLG char(1) NOT NULL,
    CTY_31_FLG char(1) NOT NULL,
    CTY_32_FLG char(1) NOT NULL,
    CTY_33_FLG char(1) NOT NULL,
    CTY_34_FLG char(1) NOT NULL,
    CTY_35_FLG char(1) NOT NULL,
    CTY_36_FLG char(1) NOT NULL,
    CTY_37_FLG char(1) NOT NULL,
    CTY_38_FLG char(1) NOT NULL,
    CTY_39_FLG char(1) NOT NULL,
    CTY_40_FLG char(1) NOT NULL,
    CTY_41_FLG char(1) NOT NULL,
    CTY_42_FLG char(1) NOT NULL,
    CTY_43_FLG char(1) NOT NULL,
    CTY_44_FLG char(1) NOT NULL,
    CTY_45_FLG char(1) NOT NULL,
    CTY_46_FLG char(1) NOT NULL,
    CTY_47_FLG char(1) NOT NULL,
    CTY_48_FLG char(1) NOT NULL,
    CTY_49_FLG char(1) NOT NULL,
    CTY_50_FLG char(1) NOT NULL,
    CTY_51_FLG char(1) NOT NULL,
    CTY_52_FLG char(1) NOT NULL,
    CTY_53_FLG char(1) NOT NULL,
    CTY_54_FLG char(1) NOT NULL,
    CTY_55_FLG char(1) NOT NULL,
    CTY_56_FLG char(1) NOT NULL,
    CTY_57_FLG char(1) NOT NULL,
    CTY_58_FLG char(1) NOT NULL,
    CTY_59_FLG char(1) NOT NULL,
    CTY_60_FLG char(1) NOT NULL,
    CTY_61_FLG char(1) NOT NULL,
    CTY_62_FLG char(1) NOT NULL,
    CTY_63_FLG char(1) NOT NULL,
    DELETE_DT date DEFAULT NULL,
    CONSTRAINT ENTITY_ID PRIMARY KEY (ENTITY_ID, ENTITY_CD)
)