-- The converted (phonetic) ADDRESS of the CLIENT or PLACEMENT HOME generated by the
-- SSA-Name3 algorithm to be used for Client Search. For each address, there could be
-- up to 25 Phonetic Keys produced by the SSA-Name3 algorithm.

CREATE TABLE ADR_PHTT
(
    PHONETC_NM char(8) NOT NULL, -- The five characters phonetic search key generated by the SSA-Name3 algorithm to be used for Address Search.
    PRMRY_NMID char(10) NOT NULL, -- ID from the entity (Placement Home) which contains the complete name of the ADDRESS for whom the Phonetic Name was defined
    PRMRY_NMCD char(1) NOT NULL, -- P
    GVR_ENTC smallint NOT NULL, -- The system generated number which represents the  specific county (e.g., Napa, Sacramento, Fresno,  etc.) within the state of California for a specific Address
    MATCH_CODE char(8) NOT NULL,
    LST_UPD_ID char(3) NOT NULL, -- The ID (a sequential 3 digit base 62 number generated by the system) of the STAFF PERSON or batch program which made the last update to an occurrence of this entity type.
    LST_UPD_TS timestamp NOT NULL, -- Current time stamp
    CONSTRAINT PK_PHONETC_NM PRIMARY KEY (PHONETC_NM, PRMRY_NMID, PRMRY_NMCD)
);
CREATE UNIQUE INDEX ADRPHT1X ON ADR_PHTT (PRMRY_NMID, PRMRY_NMCD);
CREATE UNIQUE INDEX ADRPHT2X ON ADR_PHTT (MATCH_CODE, GVR_ENTC, PRMRY_NMID, PRMRY_NMCD)