-- The converted (phonetic) Names of the SUBSTITUTE CARE PROVIDER generated by the SSA-Name3
-- algorithm to be used for Substitute Care Provider Search.    For each name, there could
-- be up to 25 Phonetic Keys produced by the SSA-Name3 algorithm.

CREATE TABLE SCP_PHTT
(
    PHONETC_NM char(8) NOT NULL, -- The five characters phonetic search key generated by the SSA-Name3 algorithm to be used for substitute Care Provider Search.
    FKSB_PVDRT char(10) NOT NULL,
    LST_UPD_ID char(3) NOT NULL, -- The ID (a sequential 3 digit base 62 number generated by the system) of the STAFF PERSON or batch program which made the last update to an occurrence of this entity type.
    LST_UPD_TS timestamp NOT NULL, -- Current time stamp
    CONSTRAINT PK_PHONETC_NM_1 PRIMARY KEY (PHONETC_NM, FKSB_PVDRT)
);
CREATE UNIQUE INDEX SCPPHT1X ON SCP_PHTT (FKSB_PVDRT)