CREATE TABLE PLCHM_UC
(
    PKPLC_HMT char(10) PRIMARY KEY NOT NULL,
    CITY_NM char(20) NOT NULL, -- residence.addresses[x].type = Residential then residence.addresses[x].city
    GEO_RGNTCD char(2) DEFAULT '' NOT NULL,
    LA_VNDR_ID char(6) DEFAULT '' NOT NULL,
    LST_UPD_ID char(3) NOT NULL, -- The ID (a sequential 3 digit base 62 number generated by the system) of the STAFF PERSON or batch program which made the last update to an occurrence of this entity type.
    LST_UPD_TS timestamp NOT NULL, -- Current time stamp
    LICENSE_NO char(9) DEFAULT '' NOT NULL,
    FACLTY_NM char(50) DEFAULT '' NOT NULL, -- applicants.applicant1.last_name + ", " + applicants.applicant1.first_name + " & " + applicants.applicant2.first_name + " RFH". A good naming convention is: Last Name, First Names followed by type of facility (e.g., J, Mary & Thomas FFH).
    STREET_NO char(10) DEFAULT '' NOT NULL, -- residence.addresses[x].type = Residential then residence.addresses[x].street_address (need to split to number and street and get only number)
    STREET_NM char(40) DEFAULT '' NOT NULL -- residence.addresses[x].type = Residential then residence.addresses[x].street_address (need to split to number and street and get only street)
);
CREATE UNIQUE INDEX PLCHMUC1 ON PLCHM_UC (CITY_NM);
CREATE UNIQUE INDEX PLCHMUC2 ON PLCHM_UC (LA_VNDR_ID);
CREATE UNIQUE INDEX PLCHMUC3 ON PLCHM_UC (LICENSE_NO);
CREATE UNIQUE INDEX PLCHMUC4 ON PLCHM_UC (FACLTY_NM);
CREATE UNIQUE INDEX PLCHMUC5 ON PLCHM_UC (STREET_NM, STREET_NO)