-- One row for each phone number in applicants.applicant.phones
CREATE TABLE PH_CNT_T
(
    THIRD_ID char(10) PRIMARY KEY NOT NULL, -- generated base on algorithm
    PHONE_NO decimal(10) NOT NULL, -- applicants.applicant.phones.phone.number
    PHEXT_NO int, -- applicants.applicant.phones.phone.extension
    PHN_TYP_CD char(1) NOT NULL, -- applicants.applicant.phones.phone.phone_type map dictionary to CWS/CMS values
    ESTBLSH_CD char(1) NOT NULL, -- S
    ESTBLSH_ID char(10) NOT NULL, -- ID from the SUBSTITUTE CARE PROVIDER entity type
    LST_UPD_ID char(3) NOT NULL, -- The ID (a sequential 3 digit base 62 number generated by the system) of the STAFF PERSON or batch program which made the last update to an occurrence of this entity type.
    LST_UPD_TS timestamp NOT NULL, -- Current time stamp
);
CREATE UNIQUE INDEX PHCNT111 ON PH_CNT_T (ESTBLSH_ID, ESTBLSH_CD, PHN_TYP_CD)