-- Background Check information about SUBSTITUTE CARE PROVIDERS, OTHER ADULTS IN
-- PLACEMENT HOME, OTHER CHILDREN IN PLACEMENT HOME and COLLATERAL INDIVIDUAL.

CREATE TABLE BKGRCHKT
(
  IDENTIFIER char(10) PRIMARY KEY NOT NULL, -- generated base on algorithm
  RCPNT_CD char(1),
  RCPNT_ID char(10),
  BKGRCHKC smallint NOT NULL,
  BKGRCHK_DT date NOT NULL,
  LST_UPD_ID char(3) NOT NULL, -- The ID (a sequential 3 digit base 62 number generated by the system) of the STAFF PERSON or batch program which made the last update to an occurrence of this entity type.
  LST_UPD_TS timestamp NOT NULL, -- Current time stamp
  FKCOLTRL_T char(10)
);
CREATE UNIQUE INDEX BKGRCHK2 ON BKGRCHKT (RCPNT_CD, RCPNT_ID);
CREATE UNIQUE INDEX BKGRCHK1 ON BKGRCHKT (FKCOLTRL_T)