CREATE TABLE CLSCP_ET
(
    IDENTIFIER char(10) PRIMARY KEY NOT NULL, -- generated base on algorithm
    ETHNCTYC smallint DEFAULT 0 NOT NULL, -- applicants.applicant.ethnicity map dictionary value to CWS/CMS code
    ESTBLSH_ID char(10) NOT NULL, -- ID from the SUBSTITUTE_CARE_PROVIDER entity types
    ESTBLSH_CD char(1) NOT NULL, -- S
    LST_UPD_ID char(3) NOT NULL, -- The ID (a sequential 3 digit base 62 number generated by the system) of the STAFF PERSON or batch program which made the last update to an occurrence of this entity type.
    LST_UPD_TS timestamp NOT NULL -- Current time stamp
);
CREATE UNIQUE INDEX CLSCP1IX ON CLSCP_ET (ESTBLSH_ID, ESTBLSH_CD)