-- Contact information to be used in the event of an emergency.
CREATE TABLE EM_CNT_T
(
    IDENTIFIER char(10) PRIMARY KEY NOT NULL, -- generated base on algorithm
    ESTBLSH_CD char(1) NOT NULL, -- P
    ESTBLSH_ID char(10) NOT NULL, -- ID from the PLACEMENT HOME
    CNTCT_NME char(35),
    PRI_PH_NO decimal(10),
    PRI_PH_EXT int,
    ALT_PH_NO decimal(10),
    ALT_PH_EXT int,
    EMAIL_ADDR char(50),
    STREET_NO char(10),
    STREET_NM char(40),
    CITY_NM char(20),
    STATE_C smallint,
    ZIP_NO int,
    ZIP_SFX_NO smallint,
    FRG_ADRT_B char(1) DEFAULT 'N' NOT NULL, -- N
    LST_UPD_ID char(3) NOT NULL, -- The ID (a sequential 3 digit base 62 number generated by the system) of the STAFF PERSON or batch program which made the last update to an occurrence of this entity type.
    LST_UPD_TS timestamp NOT NULL, -- Current time stamp
);
CREATE UNIQUE INDEX EMCNT111 ON EM_CNT_T (ESTBLSH_ID, ESTBLSH_CD)