-- create row for each minor child in RFA 1A
CREATE TABLE OTH_KIDT
(
    IDENTIFIER char(10) PRIMARY KEY NOT NULL,-- generated base on algorithm
    BIRTH_DT date, -- minor_children.date_of_birth
    GENDER_CD char(1) NOT NULL, -- minor_children.gender map to CWS/CMS code F|M
    OTHCHLD_NM char(35) NOT NULL, -- " " empty string for now
    LST_UPD_ID char(3) NOT NULL, -- The ID (a sequential 3 digit base 62 number generated by the system) of the STAFF PERSON or batch program which made the last update to an occurrence of this entity type.
    LST_UPD_TS timestamp NOT NULL, -- Current time stamp
    FKPLC_HM_T char(10) NOT NULL,
    YR_INC_AMT decimal(7,2) DEFAULT NULL
);
CREATE UNIQUE INDEX OTHKID1X ON OTH_KIDT (FKPLC_HM_T)