-- This entity type describes the relationship between a SUBSTITUTE CARE PROVIDER and other people in the PLACEMENT HOME.  These other people can be OTHER CHILDREN IN PLACEMENT or OTHER ADULTS IN PLACEMENT HOME.
CREATE TABLE OPSCPRLT
(
    IDENTIFIER char(10) PRIMARY KEY NOT NULL, -- generated base on algorithm
    CLNTRELC smallint DEFAULT 0 NOT NULL, -- relationship to applicant. Can't map for now ???
    LST_UPD_ID char(3) NOT NULL, -- The ID (a sequential 3 digit base 62 number generated by the system) of the STAFF PERSON or batch program which made the last update to an occurrence of this entity type.
    LST_UPD_TS timestamp NOT NULL, -- Current time stamp
    FKOTH_ADLT char(10) DEFAULT 'NULL',
    FKOTH_KIDT char(10) DEFAULT 'NULL',
    FKSB_PVDRT char(10) NOT NULL
);
CREATE UNIQUE INDEX OPSCPRL2 ON OPSCPRLT (FKOTH_ADLT);
CREATE UNIQUE INDEX OPSCPRL3 ON OPSCPRLT (FKOTH_KIDT);
CREATE UNIQUE INDEX OPSCPRL4 ON OPSCPRLT (FKSB_PVDRT)