CREATE TABLE HM_SCP_T
(
    THIRD_ID char(10) NOT NULL, -- generated base on algorithm
    START_DT date NOT NULL, -- Creation date
    END_DT date DEFAULT NULL, -- null
    LICNSEE_CD char(1) NOT NULL, -- U
    CRPRVDR_CD char(1) NOT NULL, -- Y
    LST_UPD_ID char(3) NOT NULL, -- The ID (a sequential 3 digit base 62 number generated by the system) of the STAFF PERSON or batch program which made the last update to an occurrence of this entity type.
    LST_UPD_TS timestamp NOT NULL, -- Current time stamp
    FKSB_PVDRT char(10) NOT NULL, -- Mandatory Foreign key that DESIGNATES a SUBSTITUTE_CARE_PROVIDER.
    FKPLC_HM_T char(10) NOT NULL, -- Mandatory Foreign key that PROVIDES_SUBSTITUTE_CARE_FOR a PLACEMENT_HOME.
    PRPRVDR_CD char(1) DEFAULT 'N' NOT NULL, -- Y for apllicants.applicant[1] and N for apllicants.applicant[2]
    CDS_PRSN char(2) DEFAULT ' ' NOT NULL,
    SCPRVD_IND char(1) NOT NULL, -- N for apllicants.applicant[1] and Y for apllicants.applicant[2]
    CONSTRAINT FKSB_PVDRT PRIMARY KEY (FKSB_PVDRT, FKPLC_HM_T, THIRD_ID)
);
CREATE UNIQUE INDEX HMSCP444 ON HM_SCP_T (FKPLC_HM_T)