-- Any general comments regarding a particular PLACEMENT HOME, documented description and
-- associated resolution of dissatisfaction about an occurrence, or feature of a licensed or
-- nonlicensed home, which has been brought to the attention of a STAFF PERSON. This general
-- information are used when reviewing homes for  potential placements.  It is the social
-- worker's  responsibility to communicate a complaint to the  licensing workers for
-- investigation when deem  necessary.
CREATE TABLE HMNOTE_T
(
    IDENTIFIER char(10) PRIMARY KEY NOT NULL, -- generated base on algorithm
    RECEIVE_DT date NOT NULL, -- creation date
    REF_LICIND char(1) NOT NULL, -- N
    SUBMITR_NM char(35) NOT NULL, -- ??? Validate in database. The name of the person who formally or informally informs a STAFF PERSON of a complaint or any additional information related to a specific licensed or nonlicensed home.
    LST_UPD_ID char(3) NOT NULL, -- The ID (a sequential 3 digit base 62 number generated by the system) of the STAFF PERSON or batch program which made the last update to an occurrence of this entity type.
    LST_UPD_TS timestamp NOT NULL, -- Current time stamp
    FKPLC_HM_T char(10) NOT NULL, -- Mandatory Foreign key that PROVIDES_ADDITIONAL_INFO_ABOUT a PLACEMENT_HOME.
    COMNT_DSC char(254) DEFAULT '' NOT NULL
);
CREATE UNIQUE INDEX HMNOTE22 ON HMNOTE_T (FKPLC_HM_T)