CREATE TABLE SBPVD_UC
(
    PKSB_PVDRT char(10) PRIMARY KEY NOT NULL,
    CA_DLIC_NO char(8) DEFAULT '' NOT NULL, -- upper case for applicants.applicant.driver_license_number
    FIRST_NM char(20) NOT NULL, -- upper case for applicants.applicant.first_name
    LAST_NM char(25) NOT NULL, -- upper case for applicants.applicant.last_name
    LST_UPD_ID char(3) NOT NULL, -- The ID (a sequential 3 digit base 62 number generated by the system) of the STAFF PERSON or batch program which made the last update to an occurrence of this entity type.
    LST_UPD_TS timestamp NOT NULL, -- Current time stamp
);
CREATE UNIQUE INDEX SBPVDUC2 ON SBPVD_UC (CA_DLIC_NO);
CREATE UNIQUE INDEX SBPVDUC1 ON SBPVD_UC (LAST_NM)