-- Each RFA 1A applicant shall be mapped to Substitute care provider entity

CREATE TABLE SB_PVDRT
(
    IDENTIFIER char(10) PRIMARY KEY NOT NULL, -- generated base on algorithm
    ADD_TEL_NO decimal(10) DEFAULT 0 NOT NULL,
    ADD_EXT_NO int DEFAULT 0 NOT NULL,
    BIRTH_DT date DEFAULT NULL, -- applicants.applicant.date_of_birth
    CA_DLIC_NO char(8) DEFAULT ' ' NOT NULL, -- applicants.applicant.driver_license_number
    CITY_NM char(20) DEFAULT ' ' NOT NULL, -- if residence.addresses[x].type = Residential then residence.addresses[x].city
    EMPLYR_NM char(35) DEFAULT ' ' NOT NULL, -- applicants.applicant.employment.employer_name
    FIRST_NM char(20) NOT NULL, -- applicants.applicant.first_name
    FRG_ADRT_B char(1) NOT NULL, -- N
    GENDER_IND char(1) NOT NULL, -- applicants.applicant.gender
    IND_TRBC smallint DEFAULT 0 NOT NULL,
    LAST_NM char(25) NOT NULL, -- applicants.applicant.last_name
    MID_INI_NM char(1) DEFAULT ' ' NOT NULL, -- first letter in upper case from applicants.applicant.middle_name
    NMPRFX_DSC char(6) DEFAULT ' ' NOT NULL, -- applicants.applicant.name_prefix.value
    SS_NO char(9) DEFAULT ' ' NOT NULL, -- rfa1b_forms.ssn
    STATE_C smallint DEFAULT 0 NOT NULL, -- residence.addresses[x].type = Mailing then residence.addresses[x].state (Map state code from CWS/CMS)
    STREET_NM char(40) DEFAULT ' ' NOT NULL, -- residence.addresses[x].type = Residential then residence.addresses[x].street_address (need to split to number and street and get only street)
    STREET_NO char(10) DEFAULT ' ' NOT NULL, -- residence.addresses[x].type = Residential then residence.addresses[x].street_address (need to split to number and street and get only number)
    SUFX_TLDSC char(4) DEFAULT ' ' NOT NULL, -- applicants.applicant.name_suffix.value
    ZIP_NO int DEFAULT 0 NOT NULL,  -- residence.addresses[x].type = Residential then residence.addresses[x].zip
    LST_UPD_ID char(3) NOT NULL, -- The ID (a sequential 3 digit base 62 number generated by the system) of the STAFF PERSON or batch program which made the last update to an occurrence of this entity type.
    LST_UPD_TS timestamp NOT NULL, -- Current time stamp
    ZIP_SFX_NO smallint DEFAULT 0 NOT NULL,
    EDUCATION smallint DEFAULT 0 NOT NULL, -- applicants.applicant.highest_education_level
    EMPL_STAT smallint DEFAULT 0 NOT NULL,
    PRIM_INC smallint DEFAULT 0 NOT NULL,
    SEC_INC smallint DEFAULT 0 NOT NULL,
    YR_INC_AMT decimal(8,2) DEFAULT 0 NOT NULL,
    HISP_CD char(1) DEFAULT ' ' NOT NULL, -- U
    MRTL_STC smallint DEFAULT 0 NOT NULL,
    LISOWNIND char(1) DEFAULT 'N' NOT NULL, -- N
    LIS_PER_ID char(10) DEFAULT 'NULL',
    EMAIL_ADDR char(50) DEFAULT 'NULL', -- applicants.applicant.email
    ETH_UD_CD char(1) DEFAULT 'NULL',
    HISP_UD_CD char(1) DEFAULT 'NULL',
    RESOST_IND char(1) DEFAULT 'NULL', -- if rfa1b_forms.lived_in_other_state == true then Y. if rfa1b_forms.lived_in_other_state == false then N. if rfa1b_forms.lived_in_other_state == null then null
    PASSBC_CD char(1) DEFAULT 'NULL'
);
CREATE UNIQUE INDEX SBPVDR3 ON SB_PVDRT (FIRST_NM, LAST_NM);
CREATE UNIQUE INDEX SBPVDR2 ON SB_PVDRT (LAST_NM, FIRST_NM)