version: "2"
prepare:
  fetch: 
    - "https://raw.githubusercontent.com/checkstyle/checkstyle/master/src/main/resources/google_checks.xml"
checks:
  argument-count:
    enabled: false
  complex-logic:
    enabled: false
  file-lines:
    enabled: false
  method-complexity:
    enabled: false
  method-count:
    enabled: false
  method-lines:
    enabled: false
  return-statements:
    enabled: false
  identical-code:
    enabled: false    
plugins:
  checkstyle:
    enabled: true
    config:
      file: "google_checks.xml"
