version: "2"
prepare:
  fetch: 
    - "https://raw.githubusercontent.com/checkstyle/checkstyle/master/src/main/resources/google_checks.xml"
checks:
  argument-count:
    enabled: true
  complex-logic:
    enabled: true
  file-lines:
    enabled: true
  method-complexity:
    enabled: true
  method-count:
    enabled: true
  method-lines:
    enabled: true
  return-statements:
    enabled: true
  identical-code:
    enabled: true
  com.puppycrawl.tools.checkstyle.checks.naming.AbbreviationAsWordInNameCheck:
    enabled: true
    
plugins:
  sonar-java:
    enabled: true
  checkstyle:
    enabled: true
    config:
      file: "google_checks.xml"
