version: '2.1'
services:
  perry:
    image: cwds/perry:1.6.1_376-RC
    hostname: perry
    ports:
      - ${PERRY_PORT}:8080
      - ${PERRY_ADMIN_PORT}:8092
    env_file: .env

  cals_db2_data:
    image: cwds/cals_db2_data
    hostname: cals_db2_data
    ports:
      - ${DB_CMS_DB2_PORT}:${DB_CMS_DB2_PORT}
    env_file: .env

  postgresql_data:
    image: cwds/postgresql_data
    hostname: postgresql_data
    ports:
      - ${DB_POSTGRES_PORT}:${DB_POSTGRES_PORT}
    env_file: .env

  cals-api:
    image: cwds/cals-api
    hostname: cals-api
    depends_on:
      cals_db2_data:
        condition: service_started
      postgresql_data:
        condition: service_started
      perry:
        condition: service_started
    restart: on-failure
    ports:
      - ${API_PORT}:8080
    env_file: .env