import gov.ca.cwds.cals.persistence.model.calsns.rfa.*
import gov.ca.cwds.cals.service.dto.rfa.*
import gov.ca.cwds.cals.Constants
import gov.ca.cwds.cals.Constants.Validation.Business;
import org.apache.commons.lang3.StringUtils

global java.util.Set validationMessages;

rule "Validate Applicant's preferred phone"
      dialect "mvel"
  agenda-group "form-submission-validation"
  when
    $form : RFA1aFormDTO()
    $applicant : ApplicantDTO(eval(StringUtils.isBlank(firstName))) from $form.applicants;
  then
      validationMessages.add(String.format(Business.APPLICANT_FIRST_NAME_IS_EMPTY,
       $applicant.getFirstName() != null ? $applicant.getFirstName() : "",
       $applicant.getLastName() != null ? $applicant.getLastName() : "",
       $applicant.getNameSuffix() != null ? $applicant.getNameSuffix().getValue() : ""));
end