import gov.ca.cwds.cals.persistence.model.calsns.rfa.RFA1aForm;
import gov.ca.cwds.cals.persistence.model.calsns.rfa.RFA1aApplicant;
import gov.ca.cwds.cals.service.dto.rfa.ApplicantDTO;
import gov.ca.cwds.cals.service.dto.rfa.PhoneDTO;
import gov.ca.cwds.cals.Constants;
import gov.ca.cwds.cals.Utils;

global java.util.Set validationMessages;

rule "Check Applicant phone numbers for duplication"
      dialect "mvel"
  agenda-group "applicant-phone-numbers-duplication-validation"
  when
      $form: RFA1aForm()
      $applicant: RFA1aApplicant() from $form.applicants
      $applicantDTO: ApplicantDTO() from $applicant.applicant
      $phone: PhoneDTO() from $applicantDTO.phones
      $otherPhone: PhoneDTO(this != $phone) from $applicantDTO.phones
      exists PhoneDTO(number == $phone.number, extension == $phone.number) from $otherPhone
  then
      validationMessages.add(String.format(Constants.Validation.Business.APPLICANT_PHONE_NUMBERS_DUPLICATION_MESSAGE,
       Utils.Phone.formatNumber($phone),
       $applicantDTO.getFirstName(),
       $applicantDTO.getLastName(),
       $applicantDTO.getNameSuffix().getValue()));
end